export const GAME_CONFIG = {
  MAX_NAME_LENGTH: 5,
  MIN_ROUND: 1,
  MAX_ROUND: 100,
  MIN_RANDOM: 0,
  MAX_RANDOM: 9,
  MIN_NAME_COUNT: 2,
  MAX_NAME_COUNT: 100,
  MOVE_THRESHOLD: 4,
  NAME_DELIMITER: ",",
  POSITION_MARK: "-",
};
